blank_issues_enabled: false
contact_links:
  - name: Ask a question or discuss ideas
    url: https://github.com/jomkz/fa-content/discussions
    about: Use GitHub Discussions for questions, ideas, and general chat
